# Create Kubernetes secrets from GCP Secret Manager
apiVersion: v1
kind: Secret
metadata:
  name: groq-api-key
  namespace: default
type: Opaque
data:
  api-key: "" # This will be populated by the deployment script

---
apiVersion: v1
kind: Secret
metadata:
  name: hf-token
  namespace: default
type: Opaque
data:
  token: "" # This will be populated by the deployment script

---
apiVersion: v1
kind: Secret
metadata:
  name: google-api-key
  namespace: default
type: Opaque
data:
  api-key: "" # This will be populated by the deployment script

---
apiVersion: v1
kind: Secret
metadata:
  name: langchain-api-key
  namespace: default
type: Opaque
data:
  api-key: "" # This will be populated by the deployment script
