faiss_db:
  collection_name: "document_portal"

# LangSmith tracking configuration
langsmith:
  enabled: true  # Set to false to disable tracking
  project_name: "DOCUMENT_PORTAL"  # Project name in LangSmith
  environment: "production"  # Environment tag for tracking

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model_name: "openai/gpt-oss-120b"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.5-flash"
    temperature: 0
    max_output_tokens: 2048